// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoDeploymentList")]
    pub struct DeploymentList(Object<ffi::OsinfoDeploymentList, ffi::OsinfoDeploymentListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_deploymentlist_get_type(),
    }
}

impl DeploymentList {
        pub const NONE: Option<&'static DeploymentList> = None;
    

    /// Construct a new deployment list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty deployment list
    #[doc(alias = "osinfo_deploymentlist_new")]
    pub fn new() -> DeploymentList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_deploymentlist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeploymentList`] objects.
            ///
            /// This method returns an instance of [`DeploymentListBuilder`](crate::builders::DeploymentListBuilder) which can be used to create [`DeploymentList`] objects.
            pub fn builder() -> DeploymentListBuilder {
                DeploymentListBuilder::new()
            }
        
}

impl Default for DeploymentList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeploymentList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeploymentListBuilder {
            builder: glib::object::ObjectBuilder<'static, DeploymentList>,
        }

        impl DeploymentListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeploymentList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeploymentList {
assert_initialized_main_thread!();
    self.builder.build() }
}
