// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoDeviceDriverList")]
    pub struct DeviceDriverList(Object<ffi::OsinfoDeviceDriverList, ffi::OsinfoDeviceDriverListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_device_driverlist_get_type(),
    }
}

impl DeviceDriverList {
        pub const NONE: Option<&'static DeviceDriverList> = None;
    

    /// Construct a new device driver list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty device driver list
    #[doc(alias = "osinfo_device_driverlist_new")]
    pub fn new() -> DeviceDriverList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_device_driverlist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceDriverList`] objects.
            ///
            /// This method returns an instance of [`DeviceDriverListBuilder`](crate::builders::DeviceDriverListBuilder) which can be used to create [`DeviceDriverList`] objects.
            pub fn builder() -> DeviceDriverListBuilder {
                DeviceDriverListBuilder::new()
            }
        
}

impl Default for DeviceDriverList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceDriverList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceDriverListBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceDriverList>,
        }

        impl DeviceDriverListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceDriverList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceDriverList {
assert_initialized_main_thread!();
    self.builder.build() }
}
