// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoDeviceList")]
    pub struct DeviceList(Object<ffi::OsinfoDeviceList, ffi::OsinfoDeviceListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_devicelist_get_type(),
    }
}

impl DeviceList {
        pub const NONE: Option<&'static DeviceList> = None;
    

    /// Construct a new device list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty device list
    #[doc(alias = "osinfo_devicelist_new")]
    pub fn new() -> DeviceList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_devicelist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`DeviceList`] objects.
            ///
            /// This method returns an instance of [`DeviceListBuilder`](crate::builders::DeviceListBuilder) which can be used to create [`DeviceList`] objects.
            pub fn builder() -> DeviceListBuilder {
                DeviceListBuilder::new()
            }
        
}

impl Default for DeviceList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`DeviceList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct DeviceListBuilder {
            builder: glib::object::ObjectBuilder<'static, DeviceList>,
        }

        impl DeviceListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`DeviceList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> DeviceList {
assert_initialized_main_thread!();
    self.builder.build() }
}
