// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*};
#[cfg(feature = "v1_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
use glib::{translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoFirmwareList")]
    pub struct FirmwareList(Object<ffi::OsinfoFirmwareList, ffi::OsinfoFirmwareListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_firmwarelist_get_type(),
    }
}

impl FirmwareList {
        pub const NONE: Option<&'static FirmwareList> = None;
    

    /// Construct a new firmware list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty firmware list
    #[cfg(feature = "v1_7")]
    #[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
    #[doc(alias = "osinfo_firmwarelist_new")]
    pub fn new() -> FirmwareList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_firmwarelist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`FirmwareList`] objects.
            ///
            /// This method returns an instance of [`FirmwareListBuilder`](crate::builders::FirmwareListBuilder) which can be used to create [`FirmwareList`] objects.
            pub fn builder() -> FirmwareListBuilder {
                FirmwareListBuilder::new()
            }
        
}

#[cfg(feature = "v1_7")]
#[cfg_attr(docsrs, doc(cfg(feature = "v1_7")))]
impl Default for FirmwareList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`FirmwareList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct FirmwareListBuilder {
            builder: glib::object::ObjectBuilder<'static, FirmwareList>,
        }

        impl FirmwareListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`FirmwareList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> FirmwareList {
assert_initialized_main_thread!();
    self.builder.build() }
}
