// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoInstallScriptList")]
    pub struct InstallScriptList(Object<ffi::OsinfoInstallScriptList, ffi::OsinfoInstallScriptListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_install_scriptlist_get_type(),
    }
}

impl InstallScriptList {
        pub const NONE: Option<&'static InstallScriptList> = None;
    

    /// Construct a new install_script list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty install_script list
    #[doc(alias = "osinfo_install_scriptlist_new")]
    pub fn new() -> InstallScriptList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_install_scriptlist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`InstallScriptList`] objects.
            ///
            /// This method returns an instance of [`InstallScriptListBuilder`](crate::builders::InstallScriptListBuilder) which can be used to create [`InstallScriptList`] objects.
            pub fn builder() -> InstallScriptListBuilder {
                InstallScriptListBuilder::new()
            }
        
}

impl Default for InstallScriptList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`InstallScriptList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct InstallScriptListBuilder {
            builder: glib::object::ObjectBuilder<'static, InstallScriptList>,
        }

        impl InstallScriptListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`InstallScriptList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> InstallScriptList {
assert_initialized_main_thread!();
    self.builder.build() }
}
