// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoProductList")]
    pub struct ProductList(Object<ffi::OsinfoProductList, ffi::OsinfoProductListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_productlist_get_type(),
    }
}

impl ProductList {
        pub const NONE: Option<&'static ProductList> = None;
    

    /// Construct a new os list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty os list
    #[doc(alias = "osinfo_productlist_new")]
    pub fn new() -> ProductList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_productlist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`ProductList`] objects.
            ///
            /// This method returns an instance of [`ProductListBuilder`](crate::builders::ProductListBuilder) which can be used to create [`ProductList`] objects.
            pub fn builder() -> ProductListBuilder {
                ProductListBuilder::new()
            }
        
}

impl Default for ProductList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`ProductList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct ProductListBuilder {
            builder: glib::object::ObjectBuilder<'static, ProductList>,
        }

        impl ProductListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`ProductList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> ProductList {
assert_initialized_main_thread!();
    self.builder.build() }
}
