// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoResourcesList")]
    pub struct ResourcesList(Object<ffi::OsinfoResourcesList, ffi::OsinfoResourcesListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_resourceslist_get_type(),
    }
}

impl ResourcesList {
        pub const NONE: Option<&'static ResourcesList> = None;
    

    /// Construct a new resources list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty resources list
    #[doc(alias = "osinfo_resourceslist_new")]
    pub fn new() -> ResourcesList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_resourceslist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`ResourcesList`] objects.
            ///
            /// This method returns an instance of [`ResourcesListBuilder`](crate::builders::ResourcesListBuilder) which can be used to create [`ResourcesList`] objects.
            pub fn builder() -> ResourcesListBuilder {
                ResourcesListBuilder::new()
            }
        
}

impl Default for ResourcesList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`ResourcesList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct ResourcesListBuilder {
            builder: glib::object::ObjectBuilder<'static, ResourcesList>,
        }

        impl ResourcesListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`ResourcesList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> ResourcesList {
assert_initialized_main_thread!();
    self.builder.build() }
}
