// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../girs
// DO NOT EDIT

use crate::{ffi,List};
use glib::{prelude::*,translate::*};

glib::wrapper! {
    ///
    ///
    /// # Implements
    ///
    /// [`ListExt`][trait@crate::prelude::ListExt]
    #[doc(alias = "OsinfoTreeList")]
    pub struct TreeList(Object<ffi::OsinfoTreeList, ffi::OsinfoTreeListClass>) @extends List;

    match fn {
        type_ => || ffi::osinfo_treelist_get_type(),
    }
}

impl TreeList {
        pub const NONE: Option<&'static TreeList> = None;
    

    /// Construct a new tree list that is initially empty.
    ///
    /// # Returns
    ///
    /// an empty tree list
    #[doc(alias = "osinfo_treelist_new")]
    pub fn new() -> TreeList {
        assert_initialized_main_thread!();
        unsafe {
            from_glib_full(ffi::osinfo_treelist_new())
        }
    }

            // rustdoc-stripper-ignore-next
            /// Creates a new builder-pattern struct instance to construct [`TreeList`] objects.
            ///
            /// This method returns an instance of [`TreeListBuilder`](crate::builders::TreeListBuilder) which can be used to create [`TreeList`] objects.
            pub fn builder() -> TreeListBuilder {
                TreeListBuilder::new()
            }
        
}

impl Default for TreeList {
                     fn default() -> Self {
                         Self::new()
                     }
                 }

// rustdoc-stripper-ignore-next
        /// A [builder-pattern] type to construct [`TreeList`] objects.
        ///
        /// [builder-pattern]: https://doc.rust-lang.org/1.0.0/style/ownership/builders.html
#[must_use = "The builder must be built to be used"]
pub struct TreeListBuilder {
            builder: glib::object::ObjectBuilder<'static, TreeList>,
        }

        impl TreeListBuilder {
        fn new() -> Self {
            Self { builder: glib::object::Object::builder() }
        }

                            /// The specialization of the list. The list will be
                            /// restricted to storing [`Entity`][crate::Entity] objects of
                            /// the specified type.
                            pub fn element_type(self, element_type: glib::types::Type) -> Self {
                            Self { builder: self.builder.property("element-type", element_type), }
                        }

    // rustdoc-stripper-ignore-next
    /// Build the [`TreeList`].
    #[must_use = "Building the object from the builder is usually expensive and is not expected to have side effects"]
    pub fn build(self) -> TreeList {
assert_initialized_main_thread!();
    self.builder.build() }
}
