// This file was generated by gir (https://github.com/gtk-rs/gir)
// from ../../girs
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "OsinfoAvatarFormat", sizeof(OsinfoAvatarFormat), alignof(OsinfoAvatarFormat));
    printf("%s;%zu;%zu\n", "OsinfoAvatarFormatClass", sizeof(OsinfoAvatarFormatClass), alignof(OsinfoAvatarFormatClass));
    printf("%s;%zu;%zu\n", "OsinfoDatamap", sizeof(OsinfoDatamap), alignof(OsinfoDatamap));
    printf("%s;%zu;%zu\n", "OsinfoDatamapClass", sizeof(OsinfoDatamapClass), alignof(OsinfoDatamapClass));
    printf("%s;%zu;%zu\n", "OsinfoDatamapList", sizeof(OsinfoDatamapList), alignof(OsinfoDatamapList));
    printf("%s;%zu;%zu\n", "OsinfoDatamapListClass", sizeof(OsinfoDatamapListClass), alignof(OsinfoDatamapListClass));
    printf("%s;%zu;%zu\n", "OsinfoDb", sizeof(OsinfoDb), alignof(OsinfoDb));
    printf("%s;%zu;%zu\n", "OsinfoDbClass", sizeof(OsinfoDbClass), alignof(OsinfoDbClass));
    printf("%s;%zu;%zu\n", "OsinfoDeployment", sizeof(OsinfoDeployment), alignof(OsinfoDeployment));
    printf("%s;%zu;%zu\n", "OsinfoDeploymentClass", sizeof(OsinfoDeploymentClass), alignof(OsinfoDeploymentClass));
    printf("%s;%zu;%zu\n", "OsinfoDeploymentList", sizeof(OsinfoDeploymentList), alignof(OsinfoDeploymentList));
    printf("%s;%zu;%zu\n", "OsinfoDeploymentListClass", sizeof(OsinfoDeploymentListClass), alignof(OsinfoDeploymentListClass));
    printf("%s;%zu;%zu\n", "OsinfoDevice", sizeof(OsinfoDevice), alignof(OsinfoDevice));
    printf("%s;%zu;%zu\n", "OsinfoDeviceClass", sizeof(OsinfoDeviceClass), alignof(OsinfoDeviceClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceDriver", sizeof(OsinfoDeviceDriver), alignof(OsinfoDeviceDriver));
    printf("%s;%zu;%zu\n", "OsinfoDeviceDriverClass", sizeof(OsinfoDeviceDriverClass), alignof(OsinfoDeviceDriverClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceDriverList", sizeof(OsinfoDeviceDriverList), alignof(OsinfoDeviceDriverList));
    printf("%s;%zu;%zu\n", "OsinfoDeviceDriverListClass", sizeof(OsinfoDeviceDriverListClass), alignof(OsinfoDeviceDriverListClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceDriverSigningReq", sizeof(OsinfoDeviceDriverSigningReq), alignof(OsinfoDeviceDriverSigningReq));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLink", sizeof(OsinfoDeviceLink), alignof(OsinfoDeviceLink));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLinkClass", sizeof(OsinfoDeviceLinkClass), alignof(OsinfoDeviceLinkClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLinkFilter", sizeof(OsinfoDeviceLinkFilter), alignof(OsinfoDeviceLinkFilter));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLinkFilterClass", sizeof(OsinfoDeviceLinkFilterClass), alignof(OsinfoDeviceLinkFilterClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLinkList", sizeof(OsinfoDeviceLinkList), alignof(OsinfoDeviceLinkList));
    printf("%s;%zu;%zu\n", "OsinfoDeviceLinkListClass", sizeof(OsinfoDeviceLinkListClass), alignof(OsinfoDeviceLinkListClass));
    printf("%s;%zu;%zu\n", "OsinfoDeviceList", sizeof(OsinfoDeviceList), alignof(OsinfoDeviceList));
    printf("%s;%zu;%zu\n", "OsinfoDeviceListClass", sizeof(OsinfoDeviceListClass), alignof(OsinfoDeviceListClass));
    printf("%s;%zu;%zu\n", "OsinfoEntity", sizeof(OsinfoEntity), alignof(OsinfoEntity));
    printf("%s;%zu;%zu\n", "OsinfoEntityClass", sizeof(OsinfoEntityClass), alignof(OsinfoEntityClass));
    printf("%s;%zu;%zu\n", "OsinfoError", sizeof(OsinfoError), alignof(OsinfoError));
    printf("%s;%zu;%zu\n", "OsinfoFilter", sizeof(OsinfoFilter), alignof(OsinfoFilter));
    printf("%s;%zu;%zu\n", "OsinfoFilterClass", sizeof(OsinfoFilterClass), alignof(OsinfoFilterClass));
    printf("%s;%zu;%zu\n", "OsinfoFirmware", sizeof(OsinfoFirmware), alignof(OsinfoFirmware));
    printf("%s;%zu;%zu\n", "OsinfoFirmwareClass", sizeof(OsinfoFirmwareClass), alignof(OsinfoFirmwareClass));
    printf("%s;%zu;%zu\n", "OsinfoFirmwareList", sizeof(OsinfoFirmwareList), alignof(OsinfoFirmwareList));
    printf("%s;%zu;%zu\n", "OsinfoFirmwareListClass", sizeof(OsinfoFirmwareListClass), alignof(OsinfoFirmwareListClass));
    printf("%s;%zu;%zu\n", "OsinfoImage", sizeof(OsinfoImage), alignof(OsinfoImage));
    printf("%s;%zu;%zu\n", "OsinfoImageClass", sizeof(OsinfoImageClass), alignof(OsinfoImageClass));
    printf("%s;%zu;%zu\n", "OsinfoImageList", sizeof(OsinfoImageList), alignof(OsinfoImageList));
    printf("%s;%zu;%zu\n", "OsinfoImageListClass", sizeof(OsinfoImageListClass), alignof(OsinfoImageListClass));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfig", sizeof(OsinfoInstallConfig), alignof(OsinfoInstallConfig));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigClass", sizeof(OsinfoInstallConfigClass), alignof(OsinfoInstallConfigClass));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigParam", sizeof(OsinfoInstallConfigParam), alignof(OsinfoInstallConfigParam));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigParamClass", sizeof(OsinfoInstallConfigParamClass), alignof(OsinfoInstallConfigParamClass));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigParamList", sizeof(OsinfoInstallConfigParamList), alignof(OsinfoInstallConfigParamList));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigParamListClass", sizeof(OsinfoInstallConfigParamListClass), alignof(OsinfoInstallConfigParamListClass));
    printf("%s;%zu;%zu\n", "OsinfoInstallConfigParamPolicy", sizeof(OsinfoInstallConfigParamPolicy), alignof(OsinfoInstallConfigParamPolicy));
    printf("%s;%zu;%zu\n", "OsinfoInstallScript", sizeof(OsinfoInstallScript), alignof(OsinfoInstallScript));
    printf("%s;%zu;%zu\n", "OsinfoInstallScriptClass", sizeof(OsinfoInstallScriptClass), alignof(OsinfoInstallScriptClass));
    printf("%s;%zu;%zu\n", "OsinfoInstallScriptInjectionMethod", sizeof(OsinfoInstallScriptInjectionMethod), alignof(OsinfoInstallScriptInjectionMethod));
    printf("%s;%zu;%zu\n", "OsinfoInstallScriptInstallationSource", sizeof(OsinfoInstallScriptInstallationSource), alignof(OsinfoInstallScriptInstallationSource));
    printf("%s;%zu;%zu\n", "OsinfoInstallScriptList", sizeof(OsinfoInstallScriptList), alignof(OsinfoInstallScriptList));
    printf("%s;%zu;%zu\n", "OsinfoInstallScriptListClass", sizeof(OsinfoInstallScriptListClass), alignof(OsinfoInstallScriptListClass));
    printf("%s;%zu;%zu\n", "OsinfoList", sizeof(OsinfoList), alignof(OsinfoList));
    printf("%s;%zu;%zu\n", "OsinfoListClass", sizeof(OsinfoListClass), alignof(OsinfoListClass));
    printf("%s;%zu;%zu\n", "OsinfoLoader", sizeof(OsinfoLoader), alignof(OsinfoLoader));
    printf("%s;%zu;%zu\n", "OsinfoLoaderClass", sizeof(OsinfoLoaderClass), alignof(OsinfoLoaderClass));
    printf("%s;%zu;%zu\n", "OsinfoMedia", sizeof(OsinfoMedia), alignof(OsinfoMedia));
    printf("%s;%zu;%zu\n", "OsinfoMediaClass", sizeof(OsinfoMediaClass), alignof(OsinfoMediaClass));
    printf("%s;%zu;%zu\n", "OsinfoMediaDetectFlags", sizeof(OsinfoMediaDetectFlags), alignof(OsinfoMediaDetectFlags));
    printf("%s;%zu;%zu\n", "OsinfoMediaError", sizeof(OsinfoMediaError), alignof(OsinfoMediaError));
    printf("%s;%zu;%zu\n", "OsinfoMediaList", sizeof(OsinfoMediaList), alignof(OsinfoMediaList));
    printf("%s;%zu;%zu\n", "OsinfoMediaListClass", sizeof(OsinfoMediaListClass), alignof(OsinfoMediaListClass));
    printf("%s;%zu;%zu\n", "OsinfoOs", sizeof(OsinfoOs), alignof(OsinfoOs));
    printf("%s;%zu;%zu\n", "OsinfoOsClass", sizeof(OsinfoOsClass), alignof(OsinfoOsClass));
    printf("%s;%zu;%zu\n", "OsinfoOsList", sizeof(OsinfoOsList), alignof(OsinfoOsList));
    printf("%s;%zu;%zu\n", "OsinfoOsListClass", sizeof(OsinfoOsListClass), alignof(OsinfoOsListClass));
    printf("%s;%zu;%zu\n", "OsinfoOsVariant", sizeof(OsinfoOsVariant), alignof(OsinfoOsVariant));
    printf("%s;%zu;%zu\n", "OsinfoOsVariantClass", sizeof(OsinfoOsVariantClass), alignof(OsinfoOsVariantClass));
    printf("%s;%zu;%zu\n", "OsinfoOsVariantList", sizeof(OsinfoOsVariantList), alignof(OsinfoOsVariantList));
    printf("%s;%zu;%zu\n", "OsinfoOsVariantListClass", sizeof(OsinfoOsVariantListClass), alignof(OsinfoOsVariantListClass));
    printf("%s;%zu;%zu\n", "OsinfoPathFormat", sizeof(OsinfoPathFormat), alignof(OsinfoPathFormat));
    printf("%s;%zu;%zu\n", "OsinfoPlatform", sizeof(OsinfoPlatform), alignof(OsinfoPlatform));
    printf("%s;%zu;%zu\n", "OsinfoPlatformClass", sizeof(OsinfoPlatformClass), alignof(OsinfoPlatformClass));
    printf("%s;%zu;%zu\n", "OsinfoPlatformList", sizeof(OsinfoPlatformList), alignof(OsinfoPlatformList));
    printf("%s;%zu;%zu\n", "OsinfoPlatformListClass", sizeof(OsinfoPlatformListClass), alignof(OsinfoPlatformListClass));
    printf("%s;%zu;%zu\n", "OsinfoProduct", sizeof(OsinfoProduct), alignof(OsinfoProduct));
    printf("%s;%zu;%zu\n", "OsinfoProductClass", sizeof(OsinfoProductClass), alignof(OsinfoProductClass));
    printf("%s;%zu;%zu\n", "OsinfoProductFilter", sizeof(OsinfoProductFilter), alignof(OsinfoProductFilter));
    printf("%s;%zu;%zu\n", "OsinfoProductFilterClass", sizeof(OsinfoProductFilterClass), alignof(OsinfoProductFilterClass));
    printf("%s;%zu;%zu\n", "OsinfoProductList", sizeof(OsinfoProductList), alignof(OsinfoProductList));
    printf("%s;%zu;%zu\n", "OsinfoProductListClass", sizeof(OsinfoProductListClass), alignof(OsinfoProductListClass));
    printf("%s;%zu;%zu\n", "OsinfoProductRelationship", sizeof(OsinfoProductRelationship), alignof(OsinfoProductRelationship));
    printf("%s;%zu;%zu\n", "OsinfoReleaseStatus", sizeof(OsinfoReleaseStatus), alignof(OsinfoReleaseStatus));
    printf("%s;%zu;%zu\n", "OsinfoResources", sizeof(OsinfoResources), alignof(OsinfoResources));
    printf("%s;%zu;%zu\n", "OsinfoResourcesClass", sizeof(OsinfoResourcesClass), alignof(OsinfoResourcesClass));
    printf("%s;%zu;%zu\n", "OsinfoResourcesList", sizeof(OsinfoResourcesList), alignof(OsinfoResourcesList));
    printf("%s;%zu;%zu\n", "OsinfoResourcesListClass", sizeof(OsinfoResourcesListClass), alignof(OsinfoResourcesListClass));
    printf("%s;%zu;%zu\n", "OsinfoTree", sizeof(OsinfoTree), alignof(OsinfoTree));
    printf("%s;%zu;%zu\n", "OsinfoTreeClass", sizeof(OsinfoTreeClass), alignof(OsinfoTreeClass));
    printf("%s;%zu;%zu\n", "OsinfoTreeError", sizeof(OsinfoTreeError), alignof(OsinfoTreeError));
    printf("%s;%zu;%zu\n", "OsinfoTreeList", sizeof(OsinfoTreeList), alignof(OsinfoTreeList));
    printf("%s;%zu;%zu\n", "OsinfoTreeListClass", sizeof(OsinfoTreeListClass), alignof(OsinfoTreeListClass));
    return 0;
}
